name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
          node_version: [16, 18, 20]
          operating_system: [ubuntu-latest, windows-latest, macos-latest] 
    runs-on: ${{ matrix.operating_system }}
    steps:
     - name: Get code
       uses: actions/checkout@v3

     - name: install node
       uses: actions/setup-node@v3 
       with:
         node-version: '${{ matrix.node_version }}'

     - name: install dependencies
       run: npm ci

     - name: run the project
       run: npm run build